### PR TITLE
Further isolation of io

### PR DESCRIPTION
**Pull request by hrj**
* moved all `printf` like functionality to `io.cpp`
* Defined a new function called `e_printf` that prints to `stderr`.

### CODE REVIEW

**Comment by hrj** [comment]
Also updated cmake.

 @szborows you might want to have a look.

**Comment by szborows** [comment]
@hrj what do you think about removing Makefiles at all?

**Comment by hrj** [comment]
@szborows Not my call to make (hah!), but I like the simplicity of `make`. Also, I am not familiar with CMake, so maintaining the [emscripten port](https://github.com/UprootLabs/poly-flif) will become difficult for me at this stage.

**Comment by szborows** [comment]
ok, didn't know about this port

**Pull request merged**
