### PR TITLE
Replaced ugly & error-prone guards with pragma once directive

### PR DESCRIPTION
**Pull request by szborows**
Emscript port also support pragma directives.

### CODE REVIEW

**Comment by sipa** [comment]
I've never seen this. Is this supported by all modern compilers?

**Comment by szborows** [comment]
Yes. See here: https://en.wikipedia.org/wiki/Pragma_once
The only one compiler that wasn't supporting this was propertiary one, but it was about 4 years ago.

**Comment by hrj** [comment]
I don't know if this is a good idea or not; but I can confirm that `emscripten` doesn't complain.

**Comment by szborows** [comment]
What is main concern here? Portability between compilers?

**Pull request merged**
