### PR TITLE
edited makefile to build on OS X

### PR DESCRIPTION
**Pull request by mredig**
uses home-brew libraries
include OS X build

### CODE REVIEW

**Comment by hrj** [comment]
At some point, it might be better to use a `configure` script :smile:

**Comment by mredig** [comment]
I'm sure it would, but I'm too much Xcode Apple fanboy to know how to do hard things like that!

**Comment by jonsneyers** [comment]
Yes, I think this is better handled with proper autoconf/automake scripts. I will accept PRs in that direction. This PR is too much ad-hoc bricolage, so I hope you don't mind I'm going to reject it.

**Comment by mredig** [comment]
No that's fine. Did you have thoughts about my other ideas for structure in the repo? Basically, move filehandling into flif.cpp, vprintf from flif.cpp into common.cpp, leaving flif-enc and flif-dec just to pass blob pointers?

**Comment by jonsneyers** [comment]
Yes, those are good ideas.

**Comment by hrj** [comment]
> vprintf from flif.cpp into common.cpp

Yeah, I missed doing that when I re-structured the code. :+1:

**Comment by mredig** [comment]
I believe I saw it in the header, but there was nothing in the cpp file, so I'm assuming you got started and forgot.

**Comment by hrj** [comment]
On Sun, Oct 4, 2015 at 8:39 PM, Michael <notifications@github.com> wrote:

> I believe I saw it in the header, but there was nothing in the cpp file,
> so I'm assuming you got started and forgot.


​I noticed it while building the emscripten port. There are couple of
cleanups that I want to suggest once I am done with the UI I am working on.​

Will post them in a day, if no one beats me to it.

**Pull request closed without merging**
